import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ZHQ | 互動式問答 Chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW" className="size-full">
      <body className={`antialiased size-full`}>{children}</body>
    </html>
  );
}
